language: node_js
node_js:
  - "8"
script:
  - npm run test
after_success:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
  email: deployer@travis-ci.org
  name: Travis CI Deployment
