language: node_js
node_js:
  - "8"
script:
  - npm run test
after_success:
  - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
